<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.type.lexer' shared service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\lexer\\lib\\Doctrine\\Common\\Lexer\\AbstractLexer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Type\\Parser\\TypeLexer.php';

return $this->services['ivory.serializer.type.lexer'] = new \Ivory\Serializer\Type\Parser\TypeLexer();
