<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.visitor.xml.deserialization' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\VisitorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\AbstractVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\AbstractGenericVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\AbstractDeserializationVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\Xml\\XmlDeserializationVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Instantiator\\InstantiatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Instantiator\\DoctrineInstantiator.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mutator\\MutatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mutator\\ReflectionMutator.php';

return $this->services['ivory.serializer.visitor.xml.deserialization'] = new \Ivory\Serializer\Visitor\Xml\XmlDeserializationVisitor(${($_ = isset($this->services['ivory.serializer.instantiator']) ? $this->services['ivory.serializer.instantiator'] : ($this->services['ivory.serializer.instantiator'] = new \Ivory\Serializer\Instantiator\DoctrineInstantiator())) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.mutator']) ? $this->services['ivory.serializer.mutator'] : ($this->services['ivory.serializer.mutator'] = new \Ivory\Serializer\Mutator\ReflectionMutator())) && false ?: '_'}, 'entry', 'key');
