<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\SerializerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Serializer.php';

return $this->services['ivory.serializer'] = new \Ivory\Serializer\Serializer(${($_ = isset($this->services['ivory.serializer.navigator.event']) ? $this->services['ivory.serializer.navigator.event'] : $this->load('getIvory_Serializer_Navigator_EventService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.registry.visitor']) ? $this->services['ivory.serializer.registry.visitor'] : $this->load('getIvory_Serializer_Registry_VisitorService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.type.parser']) ? $this->services['ivory.serializer.type.parser'] : $this->load('getIvory_Serializer_Type_ParserService.php')) && false ?: '_'});
