<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.collector.static.marker' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Collector\\AbstractCollector.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Collector\\Image\\MarkerCollector.php';

return $this->services['ivory.google_map.helper.collector.static.marker'] = new \Ivory\GoogleMap\Helper\Collector\Image\MarkerCollector(${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.marker.style']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.marker.style'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_Marker_StyleService.php')) && false ?: '_'});
