<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.visitor.yaml.serialization' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\VisitorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\AbstractVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\AbstractGenericVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\AbstractSerializationVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Visitor\\Yaml\\YamlSerializationVisitor.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Accessor\\AccessorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Accessor\\ReflectionAccessor.php';

return $this->services['ivory.serializer.visitor.yaml.serialization'] = new \Ivory\Serializer\Visitor\Yaml\YamlSerializationVisitor(${($_ = isset($this->services['ivory.serializer.accessor']) ? $this->services['ivory.serializer.accessor'] : ($this->services['ivory.serializer.accessor'] = new \Ivory\Serializer\Accessor\ReflectionAccessor())) && false ?: '_'}, 2, 4, 0);
