<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.subscriber.place.autocomplete.base.coordinate' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\AbstractSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\Place\\Base\\AutocompleteCoordinateSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Formatter\\Formatter.php';

return $this->services['ivory.google_map.helper.subscriber.place.autocomplete.base.coordinate'] = new \Ivory\GoogleMap\Helper\Subscriber\Place\Base\AutocompleteCoordinateSubscriber(${($_ = isset($this->services['ivory.google_map.helper.formatter']) ? $this->services['ivory.google_map.helper.formatter'] : ($this->services['ivory.google_map.helper.formatter'] = new \Ivory\GoogleMap\Helper\Formatter\Formatter(false))) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.collector.place.autocomplete.base.coordinate']) ? $this->services['ivory.google_map.helper.collector.place.autocomplete.base.coordinate'] : $this->load('getIvory_GoogleMap_Helper_Collector_Place_Autocomplete_Base_CoordinateService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.base.coordinate']) ? $this->services['ivory.google_map.helper.renderer.base.coordinate'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Base_CoordinateService.php')) && false ?: '_'});
