<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.cache_warmer' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\CacheWarmer\\CacheWarmerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer-bundle\\CacheWarmer\\SerializerCacheWarmer.php';

return $this->services['ivory.serializer.cache_warmer'] = new \Ivory\SerializerBundle\CacheWarmer\SerializerCacheWarmer(${($_ = isset($this->services['ivory.serializer.mapping.factory']) ? $this->services['ivory.serializer.mapping.factory'] : $this->load('getIvory_Serializer_Mapping_FactoryService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.mapping.loader']) ? $this->services['ivory.serializer.mapping.loader'] : $this->load('getIvory_Serializer_Mapping_LoaderService.php')) && false ?: '_'}, ${($_ = isset($this->services['cache.system']) ? $this->services['cache.system'] : $this->load('getCache_SystemService.php')) && false ?: '_'});
