<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.renderer.static.overlay.extendable' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Image\\Overlay\\ExtendableRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Image\\Base\\CoordinateRenderer.php';

return $this->services['ivory.google_map.helper.renderer.static.overlay.extendable'] = new \Ivory\GoogleMap\Helper\Renderer\Image\Overlay\ExtendableRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.static.base.coordinate']) ? $this->services['ivory.google_map.helper.renderer.static.base.coordinate'] : ($this->services['ivory.google_map.helper.renderer.static.base.coordinate'] = new \Ivory\GoogleMap\Helper\Renderer\Image\Base\CoordinateRenderer())) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.marker.location']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.marker.location'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_Marker_LocationService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.polyline.location']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.polyline.location'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_Polyline_LocationService.php')) && false ?: '_'});
