<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.mapping.loader' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Loader\\ClassMetadataLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Loader\\MappedClassMetadataLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Loader\\ChainClassMetadataLoader.php';

return $this->services['ivory.serializer.mapping.loader'] = new \Ivory\Serializer\Mapping\Loader\ChainClassMetadataLoader([0 => ${($_ = isset($this->services['ivory.serializer.mapping.loader.reflection']) ? $this->services['ivory.serializer.mapping.loader.reflection'] : $this->load('getIvory_Serializer_Mapping_Loader_ReflectionService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['ivory.serializer.mapping.loader.annotation']) ? $this->services['ivory.serializer.mapping.loader.annotation'] : $this->load('getIvory_Serializer_Mapping_Loader_AnnotationService.php')) && false ?: '_'}], ${($_ = isset($this->services['ivory.serializer.type.parser']) ? $this->services['ivory.serializer.type.parser'] : $this->load('getIvory_Serializer_Type_ParserService.php')) && false ?: '_'});
