<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.mapping.factory' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\ClassMetadataFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\AbstractClassMetadataFactory.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\CacheClassMetadataFactory.php';

return $this->services['ivory.serializer.mapping.factory'] = new \Ivory\Serializer\Mapping\Factory\CacheClassMetadataFactory(${($_ = isset($this->services['ivory.serializer.mapping.factory.event']) ? $this->services['ivory.serializer.mapping.factory.event'] : $this->load('getIvory_Serializer_Mapping_Factory_EventService.php')) && false ?: '_'}, ${($_ = isset($this->services['cache.system']) ? $this->services['cache.system'] : $this->load('getCache_SystemService.php')) && false ?: '_'}, 'ivory_serializer');
