<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.renderer.control.manager' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Control\\ControlManagerRenderer.php';

$this->services['ivory.google_map.helper.renderer.control.manager'] = $instance = new \Ivory\GoogleMap\Helper\Renderer\Control\ControlManagerRenderer();

$instance->addRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.control.fullscreen']) ? $this->services['ivory.google_map.helper.renderer.control.fullscreen'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Control_FullscreenService.php')) && false ?: '_'});
$instance->addRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.control.map_type']) ? $this->services['ivory.google_map.helper.renderer.control.map_type'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Control_MapTypeService.php')) && false ?: '_'});
$instance->addRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.control.rotate']) ? $this->services['ivory.google_map.helper.renderer.control.rotate'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Control_RotateService.php')) && false ?: '_'});
$instance->addRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.control.scale']) ? $this->services['ivory.google_map.helper.renderer.control.scale'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Control_ScaleService.php')) && false ?: '_'});
$instance->addRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.control.street_view']) ? $this->services['ivory.google_map.helper.renderer.control.street_view'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Control_StreetViewService.php')) && false ?: '_'});
$instance->addRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.control.zoom']) ? $this->services['ivory.google_map.helper.renderer.control.zoom'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Control_ZoomService.php')) && false ?: '_'});

return $instance;
