<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.registry.visitor' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Registry\\VisitorRegistryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Registry\\VisitorRegistry.php';

$this->services['ivory.serializer.registry.visitor'] = $instance = new \Ivory\Serializer\Registry\VisitorRegistry();

$instance->registerVisitor(1, 'csv', ${($_ = isset($this->services['ivory.serializer.visitor.csv.serialization']) ? $this->services['ivory.serializer.visitor.csv.serialization'] : $this->load('getIvory_Serializer_Visitor_Csv_SerializationService.php')) && false ?: '_'});
$instance->registerVisitor(2, 'csv', ${($_ = isset($this->services['ivory.serializer.visitor.csv.deserialization']) ? $this->services['ivory.serializer.visitor.csv.deserialization'] : $this->load('getIvory_Serializer_Visitor_Csv_DeserializationService.php')) && false ?: '_'});
$instance->registerVisitor(1, 'json', ${($_ = isset($this->services['ivory.serializer.visitor.json.serialization']) ? $this->services['ivory.serializer.visitor.json.serialization'] : $this->load('getIvory_Serializer_Visitor_Json_SerializationService.php')) && false ?: '_'});
$instance->registerVisitor(2, 'json', ${($_ = isset($this->services['ivory.serializer.visitor.json.deserialization']) ? $this->services['ivory.serializer.visitor.json.deserialization'] : $this->load('getIvory_Serializer_Visitor_Json_DeserializationService.php')) && false ?: '_'});
$instance->registerVisitor(1, 'xml', ${($_ = isset($this->services['ivory.serializer.visitor.xml.serialization']) ? $this->services['ivory.serializer.visitor.xml.serialization'] : $this->load('getIvory_Serializer_Visitor_Xml_SerializationService.php')) && false ?: '_'});
$instance->registerVisitor(2, 'xml', ${($_ = isset($this->services['ivory.serializer.visitor.xml.deserialization']) ? $this->services['ivory.serializer.visitor.xml.deserialization'] : $this->load('getIvory_Serializer_Visitor_Xml_DeserializationService.php')) && false ?: '_'});
$instance->registerVisitor(1, 'yaml', ${($_ = isset($this->services['ivory.serializer.visitor.yaml.serialization']) ? $this->services['ivory.serializer.visitor.yaml.serialization'] : $this->load('getIvory_Serializer_Visitor_Yaml_SerializationService.php')) && false ?: '_'});
$instance->registerVisitor(2, 'yaml', ${($_ = isset($this->services['ivory.serializer.visitor.yaml.deserialization']) ? $this->services['ivory.serializer.visitor.yaml.deserialization'] : $this->load('getIvory_Serializer_Visitor_Yaml_DeserializationService.php')) && false ?: '_'});

return $instance;
