<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.navigator.event' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Navigator\\NavigatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Navigator\\EventNavigator.php';

return $this->services['ivory.serializer.navigator.event'] = new \Ivory\Serializer\Navigator\EventNavigator(${($_ = isset($this->services['ivory.serializer.navigator.default']) ? $this->services['ivory.serializer.navigator.default'] : $this->load('getIvory_Serializer_Navigator_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.event.dispatcher']) ? $this->services['ivory.serializer.event.dispatcher'] : ($this->services['ivory.serializer.event.dispatcher'] = new \Symfony\Component\EventDispatcher\EventDispatcher())) && false ?: '_'});
