<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.mapping.factory.default' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\ClassMetadataFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\AbstractClassMetadataFactory.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\ClassMetadataFactory.php';

return $this->services['ivory.serializer.mapping.factory.default'] = new \Ivory\Serializer\Mapping\Factory\ClassMetadataFactory(${($_ = isset($this->services['ivory.serializer.mapping.loader']) ? $this->services['ivory.serializer.mapping.loader'] : $this->load('getIvory_Serializer_Mapping_LoaderService.php')) && false ?: '_'});
