<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.renderer.map' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\AbstractRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\AbstractJsonRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\MapRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Formatter\\Formatter.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\json-builder\\src\\JsonBuilder.php';

return $this->services['ivory.google_map.helper.renderer.map'] = new \Ivory\GoogleMap\Helper\Renderer\MapRenderer(${($_ = isset($this->services['ivory.google_map.helper.formatter']) ? $this->services['ivory.google_map.helper.formatter'] : ($this->services['ivory.google_map.helper.formatter'] = new \Ivory\GoogleMap\Helper\Formatter\Formatter(false))) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.json_builder']) ? $this->services['ivory.google_map.helper.json_builder'] : ($this->services['ivory.google_map.helper.json_builder'] = new \Ivory\JsonBuilder\JsonBuilder())) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.map_type_id']) ? $this->services['ivory.google_map.helper.renderer.map_type_id'] : $this->load('getIvory_GoogleMap_Helper_Renderer_MapTypeIdService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.control.manager']) ? $this->services['ivory.google_map.helper.renderer.control.manager'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Control_ManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.utility.requirement']) ? $this->services['ivory.google_map.helper.renderer.utility.requirement'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Utility_RequirementService.php')) && false ?: '_'});
