<?php

namespace Proxies\__CG__\NozelitesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \NozelitesBundle\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'ide', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'nom', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'lieu', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'heure', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'description', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'siteweb', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'nbparticipant', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'nbplace', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'image', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'etat', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'idc'];
        }

        return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'ide', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'nom', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'lieu', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'heure', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'description', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'siteweb', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'nbparticipant', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'nbplace', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'image', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'etat', '' . "\0" . 'NozelitesBundle\\Entity\\Evenement' . "\0" . 'idc'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIde()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIde();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIde', []);

        return parent::getIde();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu($lieu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', [$lieu]);

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', []);

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure($heure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', [$heure]);

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', []);

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteweb($siteweb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteweb', [$siteweb]);

        return parent::setSiteweb($siteweb);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteweb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteweb', []);

        return parent::getSiteweb();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbparticipant($nbparticipant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbparticipant', [$nbparticipant]);

        return parent::setNbparticipant($nbparticipant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbparticipant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbparticipant', []);

        return parent::getNbparticipant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbplace($nbplace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbplace', [$nbplace]);

        return parent::setNbplace($nbplace);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbplace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbplace', []);

        return parent::getNbplace();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdc', []);

        return parent::getIdc();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdc($idc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdc', [$idc]);

        return parent::setIdc($idc);
    }

}
