offre_homepage:
    path:     /
    defaults: { _controller: OffreBundle:Default:index }

offre_liste:
    path:     /showoffres
    defaults: { _controller: OffreBundle:Offre:consulterOffres }

offre_liste_back:
    path:     /showoffresback
    defaults: { _controller: OffreBundle:Offre:consulterOffresBack }

offre_liste_membre:
    path:     /showoffresmembre
    defaults: { _controller: OffreBundle:Offre:consulterOffresMembre }

offre_accepter:
    path:     /accepterOffre/{id}
    defaults: { _controller: OffreBundle:Offre:accepterOffre }

offre_refuser:
    path:     /refuserOffre/{id}
    defaults: { _controller: OffreBundle:Offre:refuserOffre }

offre_supprimer:
    path:     /supprimeroffre/{id}
    defaults: { _controller: OffreBundle:Offre:delete }

offre_ajouter:
    path:     /ajouteroffre
    defaults: { _controller: OffreBundle:Offre:new }

offre_modifier:
    path:     /modifieroffre/{id}
    defaults: { _controller: OffreBundle:Offre:update }

message_liste:
    path:     /showmessages
    defaults: { _controller: OffreBundle:Message:consulterMessages }

message_liste_envoyes:
    path:     /showmessagesenvoyes
    defaults: { _controller: OffreBundle:Message:consulterMessagesEnvoyes }

message_supprimer:
    path:     /supprimermessage/{id}
    defaults: { _controller: OffreBundle:Message:delete }

message_ajouter:
    path:     /ajoutermessage
    defaults: { _controller: OffreBundle:Message:new }

message_showone:
    path:     /showonemessage{id}
    defaults: { _controller: OffreBundle:Message:consulterOneMessage }

message_repondre:
    path:     /repondremessage{id}
    defaults: { _controller: OffreBundle:Message:repondre }

message_transferer:
    path:     /transferermessage{id}
    defaults: { _controller: OffreBundle:Message:transferer }

json_offre_all:
    path:     /jsonAll
    defaults: { _controller: OffreBundle:Offre:JsonAll }

json_accepter:
    path:     /jsonAccepter{id}
    defaults: { _controller: OffreBundle:Offre:JsonAccepter }

json_refuser:
    path:     /jsonRefuser{id}
    defaults: { _controller: OffreBundle:Offre:JsonRefuser }

json_message_lastid:
    path:     /message/jsonlastid
    defaults: { _controller: OffreBundle:Message:Jsonlastid }

json_message_idbyemail:
    path:     /message/jsonidbyemail/{email}
    defaults: { _controller: OffreBundle:Message:Jsonidbyemail }

json_message_all:
    path:     /message/jsonAll
    defaults: { _controller: OffreBundle:Message:JsonAll }

json_message_add:
    path:     /message/jsonadd/{id}/{idMembre}/{idDest}/{objet}/{texte}
    defaults: { _controller: OffreBundle:Message:JsonAdd }

json_message_delete:
    path:     /message/jsondelete{id}
    defaults: { _controller: OffreBundle:Message:JsonDelete }