offre_homepage:
    path:     /
    defaults: { _controller: OffreBundle:Default:index }

offre_liste:
    path:     /showoffres
    defaults: { _controller: OffreBundle:Offre:consulterOffres }

offre_supprimer:
    path:     /supprimeroffre/{id}
    defaults: { _controller: OffreBundle:Offre:delete }

offre_ajouter:
    path:     /ajouteroffre
    defaults: { _controller: OffreBundle:Offre:new }

offre_modifier:
    path:     /modifieroffre/{id}
    defaults: { _controller: OffreBundle:Offre:update }
