reclamation_homepage:
    path:     /index
    defaults: { _controller: ReclamationBundle:Default:index }

Ajouter:
    path:     /AjoutReclamation
    defaults: { _controller: ReclamationBundle:Reclamation:Ajouter }

reclamation_show:
    path:     /AfficheReclamation
    defaults: { _controller: ReclamationBundle:Reclamation:AfficheRec }

DeleteREC:
    path:     /DeleteReclamation/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Delete }

UpdateREC:
    path:     /UpdateReclamation/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Update }

nozelites_homepagebac:
    path:     /back
    defaults: { _controller: ReclamationBundle:Reclamation:AfficheRec1 }

Ajouter1:
    path:     /AjoutReclamation1/{id}/{type}
    defaults: { _controller: ReclamationBundle:Reclamation:Ajouter1 }


Traiter:
    path:     /TraiterReclamation/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Traiter }

Deletebac:
    path:     /DeleteBack/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:Deleteback }

AjouterNote:
    path:     /AjoutNote/{id}
    defaults: { _controller: ReclamationBundle:Evaluation:AjoutNote }

AjouterNoteTest:
    path:     /AjoutNoteTest/{id}
    defaults: { _controller: ReclamationBundle:Evaluation:AjoutNoteTest }

AfficherNote:
    path:     /AfficherNote/{id}
    defaults: { _controller: ReclamationBundle:Evaluation:AfficherNote }

json_Reclamation_all:
    path:     /reclamation/jsonAll
    defaults: { _controller: ReclamationBundle:Reclamation:JsonAll }

json_groupe_find:
    path:     /reclamation/jsonFind/{id}
    defaults: { _controller: ReclamationBundle:Reclamation:JsonFind }

json_Reclamation_add:
    path:      /reclamation/jsonadd/{id_emeteur}/{id_cible}/{description}/{selecteur}
    defaults: { _controller: ReclamationBundle:Reclamation:JsonAdd }

json_Reclamation_delete:
    path:     /reclamation/jsondelete/{idRecl}
    defaults: { _controller: ReclamationBundle:Reclamation:JsonDelete }

json_Reclamation_edit:
    path:     /reclamation/jsonedit/{idRecl}/{description}
    defaults: { _controller: ReclamationBundle:Reclamation:JsonEdit }

json_Evaluation_add:
    path:      /reclamation/jsonadd/{id_r}/{rating}
    defaults: { _controller: ReclamationBundle:Evaluation:JsonAdd }