user_homepage:
    path:     /homepage
    defaults: { _controller: UserBundle:Default:index }
formation_supp:
    path:     /supprimerFormation/{id}
    defaults: { _controller: UserBundle:Formation:supprimerFormation }

user_list:
    path:     /listUser
    defaults: { _controller: UserBundle:User:ShowUser }

user_adminUserBack:
    path:     /listUserBack
    defaults: { _controller: UserBundle:User:ShowUserBack }
user_blockUser:
    path:     /blockUser/{id}
    defaults: { _controller: UserBundle:User:blockUser }

user_rechFormation:
    path:    /userFormation
    defaults: { _controller: UserBundle:User:showUserFormation}

user_single:
    path:     /singleUser/{id}
    defaults: { _controller: UserBundle:User:afficherUnUser }

json_membre_all:
    path:     /membres/jsonAll
    defaults: { _controller: UserBundle:User:JsonAll }

json_membre_add:
    path:     /membres/jsonAdd/{nom}/{prenom}/{age}/{tel}/{login}/{mdp}/{email}/{image}
    defaults: { _controller: UserBundle:User:JsonAdd }

json_membre_show:
    path:     /membres/jsonShow/{id}
    defaults: { _controller: UserBundle:User:JsonShow }

json_membre_edit:
    path:     /membres/jsonEdit/{id}/{nom}/{prenom}/{age}/{email}/{tel}
    defaults: { _controller: UserBundle:User:JsonEdit }