<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrhuuet\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrhuuet/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCrhuuet.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCrhuuet\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCrhuuet\appProdProjectContainer([
    'container.build_hash' => 'Crhuuet',
    'container.build_id' => '28e2689e',
    'container.build_time' => 1587234339,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrhuuet');
