<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxyxrqg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxyxrqg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxyxrqg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxyxrqg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXxyxrqg\appProdProjectContainer([
    'container.build_hash' => 'Xxyxrqg',
    'container.build_id' => '1d9190df',
    'container.build_time' => 1584449462,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxyxrqg');
