<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5vlfee0\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5vlfee0/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5vlfee0.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5vlfee0\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5vlfee0\appProdProjectContainer([
    'container.build_hash' => '5vlfee0',
    'container.build_id' => '7209e81d',
    'container.build_time' => 1587218234,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5vlfee0');
