<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.mutator' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mutator\\MutatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mutator\\ReflectionMutator.php';

return $this->services['ivory.serializer.mutator'] = new \Ivory\Serializer\Mutator\ReflectionMutator();
