<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.renderer.static.overlay.marker' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Image\\Overlay\\MarkerRenderer.php';

return $this->services['ivory.google_map.helper.renderer.static.overlay.marker'] = new \Ivory\GoogleMap\Helper\Renderer\Image\Overlay\MarkerRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.marker.style']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.marker.style'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_Marker_StyleService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.marker.location']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.marker.location'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_Marker_LocationService.php')) && false ?: '_'});
