<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.subscriber.place.autocomplete_javascript' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\AbstractSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\DelegateSubscriberInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\AbstractDelegateSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\Place\\AutocompleteJavascriptSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Formatter\\Formatter.php';

return $this->services['ivory.google_map.helper.subscriber.place.autocomplete_javascript'] = new \Ivory\GoogleMap\Helper\Subscriber\Place\AutocompleteJavascriptSubscriber(${($_ = isset($this->services['ivory.google_map.helper.formatter']) ? $this->services['ivory.google_map.helper.formatter'] : ($this->services['ivory.google_map.helper.formatter'] = new \Ivory\GoogleMap\Helper\Formatter\Formatter(true))) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.place.autocomplete']) ? $this->services['ivory.google_map.helper.renderer.place.autocomplete'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Place_AutocompleteService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.utility.callback']) ? $this->services['ivory.google_map.helper.renderer.utility.callback'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Utility_CallbackService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.html.javascript_tag']) ? $this->services['ivory.google_map.helper.renderer.html.javascript_tag'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Html_JavascriptTagService.php')) && false ?: '_'});
