<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.subscriber.static.marker' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\Image\\MarkerSubscriber.php';

return $this->services['ivory.google_map.helper.subscriber.static.marker'] = new \Ivory\GoogleMap\Helper\Subscriber\Image\MarkerSubscriber(${($_ = isset($this->services['ivory.google_map.helper.collector.static.marker']) ? $this->services['ivory.google_map.helper.collector.static.marker'] : $this->load('getIvory_GoogleMap_Helper_Collector_Static_MarkerService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.marker']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.marker'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_MarkerService.php')) && false ?: '_'});
