<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.mapping.factory.event' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\ClassMetadataFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Factory\\EventClassMetadataFactory.php';

return $this->services['ivory.serializer.mapping.factory.event'] = new \Ivory\Serializer\Mapping\Factory\EventClassMetadataFactory(${($_ = isset($this->services['ivory.serializer.mapping.factory.default']) ? $this->services['ivory.serializer.mapping.factory.default'] : $this->load('getIvory_Serializer_Mapping_Factory_DefaultService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.event.dispatcher']) ? $this->services['ivory.serializer.event.dispatcher'] : ($this->services['ivory.serializer.event.dispatcher'] = new \Symfony\Component\EventDispatcher\EventDispatcher())) && false ?: '_'});
