<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.renderer.static.overlay.polyline' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Image\\Overlay\\PolylineRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Image\\Overlay\\AbstractStyleRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Image\\Overlay\\AbstractPolylineStyleRenderer.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Renderer\\Image\\Overlay\\PolylineStyleRenderer.php';

return $this->services['ivory.google_map.helper.renderer.static.overlay.polyline'] = new \Ivory\GoogleMap\Helper\Renderer\Image\Overlay\PolylineRenderer(${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.polyline.style']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.polyline.style'] : ($this->services['ivory.google_map.helper.renderer.static.overlay.polyline.style'] = new \Ivory\GoogleMap\Helper\Renderer\Image\Overlay\PolylineStyleRenderer())) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.polyline.location']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.polyline.location'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_Polyline_LocationService.php')) && false ?: '_'});
