<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.navigator.default' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Navigator\\NavigatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Navigator\\Navigator.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Type\\Guesser\\TypeGuesserInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Type\\Guesser\\TypeGuesser.php';

return $this->services['ivory.serializer.navigator.default'] = new \Ivory\Serializer\Navigator\Navigator(${($_ = isset($this->services['ivory.serializer.registry.type']) ? $this->services['ivory.serializer.registry.type'] : $this->load('getIvory_Serializer_Registry_TypeService.php')) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.type.guesser']) ? $this->services['ivory.serializer.type.guesser'] : ($this->services['ivory.serializer.type.guesser'] = new \Ivory\Serializer\Type\Guesser\TypeGuesser())) && false ?: '_'});
