<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.subscriber.static.encoded_polyline' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\Image\\EncodedPolylineSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Collector\\AbstractCollector.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Collector\\Image\\EncodedPolylineCollector.php';

return $this->services['ivory.google_map.helper.subscriber.static.encoded_polyline'] = new \Ivory\GoogleMap\Helper\Subscriber\Image\EncodedPolylineSubscriber(${($_ = isset($this->services['ivory.google_map.helper.collector.static.encoded_polyline']) ? $this->services['ivory.google_map.helper.collector.static.encoded_polyline'] : ($this->services['ivory.google_map.helper.collector.static.encoded_polyline'] = new \Ivory\GoogleMap\Helper\Collector\Image\EncodedPolylineCollector())) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.encoded_polyline']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.encoded_polyline'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_EncodedPolylineService.php')) && false ?: '_'});
