<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.serializer.mapping.loader.annotation' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Loader\\ClassMetadataLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Loader\\AbstractClassMetadataLoader.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Loader\\AbstractReflectionClassMetadataLoader.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\serializer\\src\\Mapping\\Loader\\AnnotationClassMetadataLoader.php';

return $this->services['ivory.serializer.mapping.loader.annotation'] = new \Ivory\Serializer\Mapping\Loader\AnnotationClassMetadataLoader(${($_ = isset($this->services['annotation_reader']) ? $this->services['annotation_reader'] : $this->getAnnotationReaderService()) && false ?: '_'}, ${($_ = isset($this->services['ivory.serializer.type.parser']) ? $this->services['ivory.serializer.type.parser'] : $this->load('getIvory_Serializer_Type_ParserService.php')) && false ?: '_'});
