<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ivory.google_map.helper.subscriber.static.extendable' shared service.

include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Subscriber\\Image\\ExtendableSubscriber.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Collector\\AbstractCollector.php';
include_once $this->targetDirs[3].'\\vendor\\egeloen\\google-map\\src\\Helper\\Collector\\Image\\ExtendableCollector.php';

return $this->services['ivory.google_map.helper.subscriber.static.extendable'] = new \Ivory\GoogleMap\Helper\Subscriber\Image\ExtendableSubscriber(${($_ = isset($this->services['ivory.google_map.helper.collector.static.extendable']) ? $this->services['ivory.google_map.helper.collector.static.extendable'] : ($this->services['ivory.google_map.helper.collector.static.extendable'] = new \Ivory\GoogleMap\Helper\Collector\Image\ExtendableCollector())) && false ?: '_'}, ${($_ = isset($this->services['ivory.google_map.helper.renderer.static.overlay.extendable']) ? $this->services['ivory.google_map.helper.renderer.static.overlay.extendable'] : $this->load('getIvory_GoogleMap_Helper_Renderer_Static_Overlay_ExtendableService.php')) && false ?: '_'});
