<?php

namespace Proxies\__CG__\NozelitesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offre extends \NozelitesBundle\Entity\Offre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'id', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'type', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'entreprise', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'domaine', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'poste', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'requis', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'description', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'etat', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'idemetteur', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'idrecepteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'id', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'type', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'entreprise', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'domaine', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'poste', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'requis', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'description', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'etat', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'idemetteur', '' . "\0" . 'NozelitesBundle\\Entity\\Offre' . "\0" . 'idrecepteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise($entreprise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', [$entreprise]);

        return parent::setEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', []);

        return parent::getEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaine($domaine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaine', [$domaine]);

        return parent::setDomaine($domaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaine', []);

        return parent::getDomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoste($poste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoste', [$poste]);

        return parent::setPoste($poste);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste', []);

        return parent::getPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequis($requis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequis', [$requis]);

        return parent::setRequis($requis);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequis', []);

        return parent::getRequis();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdemetteur(\NozelitesBundle\Entity\ChasseurTalent $idemetteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdemetteur', [$idemetteur]);

        return parent::setIdemetteur($idemetteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdemetteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdemetteur', []);

        return parent::getIdemetteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrecepteur(\NozelitesBundle\Entity\Membre $idrecepteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrecepteur', [$idrecepteur]);

        return parent::setIdrecepteur($idrecepteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdrecepteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrecepteur', []);

        return parent::getIdrecepteur();
    }

}
