<?php

namespace Proxies\__CG__\ReclamationBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reclamation extends \ReclamationBundle\Entity\Reclamation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'idrecl', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'idEmeteur', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'idCible', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'description', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'etat', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'selecteur', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'date'];
        }

        return ['__isInitialized__', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'idrecl', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'idEmeteur', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'idCible', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'description', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'etat', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'selecteur', '' . "\0" . 'ReclamationBundle\\Entity\\Reclamation' . "\0" . 'date'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reclamation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdrecl()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdrecl();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdrecl', []);

        return parent::getIdrecl();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdrecl($idrecl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdrecl', [$idrecl]);

        return parent::setIdrecl($idrecl);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmeteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmeteur', []);

        return parent::getIdEmeteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmeteur($idEmeteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmeteur', [$idEmeteur]);

        return parent::setIdEmeteur($idEmeteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCible', []);

        return parent::getIdCible();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCible($idCible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCible', [$idCible]);

        return parent::setIdCible($idCible);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function isEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEtat', []);

        return parent::isEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat($etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getSelecteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelecteur', []);

        return parent::getSelecteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setSelecteur($selecteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSelecteur', [$selecteur]);

        return parent::setSelecteur($selecteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

}
