<?php

namespace Proxies\__CG__\NozelitesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Listediplome extends \NozelitesBundle\Entity\Listediplome implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'idDiplome', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'organisation', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'domaine', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'idMembre', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'Membre'];
        }

        return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'idDiplome', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'organisation', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'domaine', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'idMembre', '' . "\0" . 'NozelitesBundle\\Entity\\Listediplome' . "\0" . 'Membre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Listediplome $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdDiplome()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDiplome();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDiplome', []);

        return parent::getIdDiplome();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganisation($organisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganisation', [$organisation]);

        return parent::setOrganisation($organisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganisation', []);

        return parent::getOrganisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomaine($domaine)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomaine', [$domaine]);

        return parent::setDomaine($domaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomaine', []);

        return parent::getDomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMembre(\NozelitesBundle\Entity\Membre $idMembre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMembre', [$idMembre]);

        return parent::setIdMembre($idMembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMembre', []);

        return parent::getIdMembre();
    }

}
