<?php

namespace Proxies\__CG__\NozelitesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Publication extends \NozelitesBundle\Entity\Publication implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'id', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'titre', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'description', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'image', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'idGroupe', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'idPublicateur', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'nbJaime'];
        }

        return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'id', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'titre', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'description', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'image', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'idGroupe', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'idPublicateur', '' . "\0" . 'NozelitesBundle\\Entity\\Publication' . "\0" . 'nbJaime'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Publication $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdGroupe($idGroupe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdGroupe', [$idGroupe]);

        return parent::setIdGroupe($idGroupe);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdGroupe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdGroupe', []);

        return parent::getIdGroupe();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPublicateur($idPublicateur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPublicateur', [$idPublicateur]);

        return parent::setIdPublicateur($idPublicateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPublicateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPublicateur', []);

        return parent::getIdPublicateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbJaime($nbJaime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbJaime', [$nbJaime]);

        return parent::setNbJaime($nbJaime);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbJaime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbJaime', []);

        return parent::getNbJaime();
    }

}
