<?php

namespace Proxies\__CG__\NozelitesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \NozelitesBundle\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'idmessage', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'objet', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'texte', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'idDestinataire', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'idEmeteur'];
        }

        return ['__isInitialized__', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'idmessage', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'objet', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'texte', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'date', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'idDestinataire', '' . "\0" . 'NozelitesBundle\\Entity\\Message' . "\0" . 'idEmeteur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdmessage()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmessage();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmessage', []);

        return parent::getIdmessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmessage($idmessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmessage', [$idmessage]);

        return parent::setIdmessage($idmessage);
    }

    /**
     * {@inheritDoc}
     */
    public function setObjet($objet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjet', [$objet]);

        return parent::setObjet($objet);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjet', []);

        return parent::getObjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexte($texte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexte', [$texte]);

        return parent::setTexte($texte);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexte', []);

        return parent::getTexte();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDestinataire(\NozelitesBundle\Entity\Membre $idDestinataire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDestinataire', [$idDestinataire]);

        return parent::setIdDestinataire($idDestinataire);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDestinataire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDestinataire', []);

        return parent::getIdDestinataire();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdEmeteur(\NozelitesBundle\Entity\Membre $idEmeteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdEmeteur', [$idEmeteur]);

        return parent::setIdEmeteur($idEmeteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdEmeteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdEmeteur', []);

        return parent::getIdEmeteur();
    }

}
