
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

nozelites_listparticipant:
    resource: "@NozelitesBundle/Controller/ListparticipantController.php"
    type:     annotation

nozelites_evenement:
    resource: "@NozelitesBundle/Controller/EvenementController.php"
    type:     annotation

offre:
    resource: "@OffreBundle/Resources/config/routing.yml"
    prefix:   /offre

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation


nozelites_groupe_membre:
    resource: "@NozelitesBundle/Controller/GroupeMembreController.php"
    type:     annotation

nozelites_groupe:
    resource: "@NozelitesBundle/Controller/GroupeController.php"
    type:     annotation

nozelites:
    resource: "@NozelitesBundle/Resources/config/routing.yml"
    prefix:   /

publication:
    resource: "@PublicationBundle/Resources/config/routing.yml"
    prefix:   /publication

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"