<?php

namespace UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByName($name){
        $query=$this->getEntityManager()
            ->createQuery("SELECT user FROM UserBundle:User user WHERE user.nom = :recherche")
            ->setParameter('recherche',$name);
        return $query->getResult();
    }

}
