<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2mw9czp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2mw9czp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2mw9czp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2mw9czp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2mw9czp\appDevDebugProjectContainer([
    'container.build_hash' => '2mw9czp',
    'container.build_id' => '1174f977',
    'container.build_time' => 1586701608,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2mw9czp');
