<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXw5tmtv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXw5tmtv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXw5tmtv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXw5tmtv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXw5tmtv\appDevDebugProjectContainer([
    'container.build_hash' => 'Xw5tmtv',
    'container.build_id' => '83c26ef4',
    'container.build_time' => 1585604448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXw5tmtv');
