<?php

namespace NozelitesBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMembreByEmail($mail){
        $query=$this->getEntityManager()
            ->createQuery("SELECT membre FROM NozelitesBundle:Membre membre WHERE membre.mail = :mail")
            ->setParameter('mail',$mail);
        return $query->getResult();
    }
}